name: 'Build Twasi Plugin'
description: 'Build your Twasi Plugin'
author: 'Twasi'
inputs: 
  plugin-name:
    description: 'The name of the plugin'
    required: true
runs:
  using: 'node12'
  main: 'lib/build-twasi-plugin.js'
