name: Main workflow
on: [push]
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Node.js 10.x
      uses: actions/setup-node@master
      with:
        node-version: 10.x

    - name: Install packages
      run: yarn

    - name: Build
      run: yarn run build

    - name: Remove gitignore
      run: rm .gitignore

    - name: Commit
      run: git config user.email info@twasi.net && git config user.name "Twasi CICD" && git add -A && git commit -m "deployment"

    - name: Push to github
      run: git push https://${{secrets.GH_USER}}:${{secrets.GH_TOKEN}}@github.com/Twasi/build-twasi-plugin.git HEAD:deployment